### ISSUE TITLE
最好把临时文件都删掉，方便下载

### ISSUE THREAD

**Issue by vkensou** [OtakuAndFitness/TechnicalNote#2]

**Comment by OtakuAndFitness** [comment]
其实没有临时文件，都是些我做了一半或者开了个头的东西，由于这个那个的原因没完成，等完成了会写成博客的

**Comment by vkensou** [comment]
> 其实没有临时文件，都是些我做了一半或者开了个头的东西，由于这个那个的原因没完成，等完成了会写成博客的

Unity项目下除了Assets、Packages和ProjectSettings文件夹，其他的都是临时文件

**Comment by OtakuAndFitness** [comment]
不好意思，那些个人习惯是不删的

**Comment by vkensou** [comment]
> 不好意思，那些个人习惯是不删的

这些东西你本地可以留着，而且实在是不方便下载，github下载速度本来就慢。你发github上不就是为了分享么。

**Comment by OtakuAndFitness** [comment]
我明天来开个精简版的分支吧，就留Assets、Packages和ProjectSettings文件夹

**Comment by OtakuAndFitness** [comment]
我弄了个lite分支，下载慢的话可以用https://www.gitclone.com/ 试试提速
